config/routes.rb
Rails.application.routes.draw do
  root 'main#get'

  get :admin, to: 'admin/admin_main#get'
  scope '/admin', module: 'admin' do
    resources :product_packeds, as: 'product_packeds'
    resources :products, as: 'products'
    resources :categories, as: 'categories'
  end
end

app/models/product_packed.rb
class ProductPacked < Product

  # Following fields are compulsory:
  # id (implicitelly defined by MongoMapper),
  # name (string), description (markdown or html_safe).
  # key :name, String, :required => true
  # key :description, String, :required => true

  # Other fields, that might not be used by
  # inherited classes:
  # key :url, String
  # key :quantity, Float
  # key :price, Float

  field :quantity_packed,   type: Float
  field :quantity_unpacked, type: Float
  field :price_packed,      type: Float
  field :price_unpacked,    type: Float
  field :packing,           type: Float
  field :weight_unpacked,   type: Float
  field :weight_packed,     type: Float

  # Method show_price must be defined in every subclass and must
  # show the price as it is displayed in the product view
  # The method must return string, and it can be HTML
  # (in that case method should mark it as safe).
  #
  # Parameter options defines how the price should be formated
  # (max_number_of_lines, short, long, list_view etc. Currently
  # not used, but will be defined here as views are being
  # made).
  def show_price(options = {})
    price_unpacked.to_s + '€ per piece, ' + price_packed.to_s + '€ per box'
  end

  # Similarlyto show_price, this method should show available
  # quantities of the product as text. If too complicated, return
  # nil and quantities will not be shown
  def show_quantity(options = {})
    quantity_packed.to_s + 'boxes + ' + quantity_unpacked.to_s + 'pcs available'
  end

  #def calc_price(quantity, options = {})
  #  price * quantity
  #end
end

app/controllers/admin/product_packeds_controller.rb
class Admin::ProductPackedsController < Admin::AdminController
  before_action :set_product_packed, only: [:show, :edit, :update, :destroy]

  # GET /product_packeds
  # GET /product_packeds.json
  def index
    @product_packeds = ProductPacked.all
  end

  # GET /product_packeds/1
  # GET /product_packeds/1.json
  def show
  end

  # GET /product_packeds/new
  def new
    @product_packed = ProductPacked.new
  end

  # GET /product_packeds/1/edit
  def edit
  end

  # POST /product_packeds
  # POST /product_packeds.json
  def create
    @product_packed = ProductPacked.new(product_packed_params)

    respond_to do |format|
      if @product_packed.save
        format.html { redirect_to @product_packed, notice: 'Product packed was successfully created.' }
        format.json { render :show, status: :created, location: @product_packed }
      else
        format.html { render :new }
        format.json { render json: @product_packed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_packeds/1
  # PATCH/PUT /product_packeds/1.json
  def update
    respond_to do |format|
      if @product_packed.update(product_packed_params)
        format.html { redirect_to @product_packed, notice: 'Product packed was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_packed }
      else
        format.html { render :edit }
        format.json { render json: @product_packed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_packeds/1
  # DELETE /product_packeds/1.json
  def destroy
    @product_packed.destroy
    respond_to do |format|
      format.html { redirect_to product_packeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_packed
      @product_packed = ProductPacked.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_packed_params
      params.require(:product_packed).permit(:id, :name, :description, :url, :quantity_packed, :quantity_unpacked, :price_packed, :price_unpacked)
    end
end

app/controllers/product_packeds_controller.rb
class ProductPackedsController < ApplicationController
  before_action :set_product_packed, only: [:show, :edit, :update, :destroy]

  # GET /product_packeds
  # GET /product_packeds.json
  def index
    @product_packeds = ProductPacked.all
  end

  # GET /product_packeds/1
  # GET /product_packeds/1.json
  def show
  end

  # GET /product_packeds/new
  def new
    @product_packed = ProductPacked.new
  end

  # GET /product_packeds/1/edit
  def edit
  end

  # POST /product_packeds
  # POST /product_packeds.json
  def create
    @product_packed = ProductPacked.new(product_packed_params)

    respond_to do |format|
      if @product_packed.save
        format.html { redirect_to @product_packed, notice: 'Product packed was successfully created.' }
        format.json { render :show, status: :created, location: @product_packed }
      else
        format.html { render :new }
        format.json { render json: @product_packed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_packeds/1
  # PATCH/PUT /product_packeds/1.json
  def update
    respond_to do |format|
      if @product_packed.update(product_packed_params)
        format.html { redirect_to @product_packed, notice: 'Product packed was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_packed }
      else
        format.html { render :edit }
        format.json { render json: @product_packed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_packeds/1
  # DELETE /product_packeds/1.json
  def destroy
    @product_packed.destroy
    respond_to do |format|
      format.html { redirect_to product_packeds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_packed
      @product_packed = ProductPacked.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_packed_params
      params.require(:product_packed).permit(:id, :name, :description, :url, :quantity_packed, :quantity_unpacked, :price_packed, :price_unpacked)
    end
end

app/helpers/product_packeds_helper.rb
module ProductPackedsHelper
end

app/views/admin/product_packeds/_form.html.haml
= form_for(@product_packed) do |f|
  - if @product_packed.errors.any?
    #error_explanation
      %h2
        = pluralize(@product_packed.errors.count, "error")
        prohibited this product_packed from being saved:
      %ul
        - @product_packed.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :id
    %br/
    = f.number_field :id
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :url
    %br/
    = f.text_field :url
  .field
    = f.label :quantity_packed
    %br/
    = f.text_field :quantity_packed
  .field
    = f.label :quantity_unpacked
    %br/
    = f.text_field :quantity_unpacked
  .field
    = f.label :price_packed
    %br/
    = f.text_field :price_packed
  .field
    = f.label :price_unpacked
    %br/
    = f.text_field :price_unpacked
  .actions
    = f.submit

app/views/admin/product_packeds/edit.html.haml
%h1 Editing product_packed
= render 'form'
= link_to 'Show', @product_packed
|
\#{link_to 'Back', product_packeds_path}

app/views/admin/product_packeds/index.html.haml
%h1 Listing product_packeds
%table
  %thead
    %tr
      %th Id
      %th Name
      %th Description
      %th Url
      %th Quantity packed
      %th Quantity unpacked
      %th Price packed
      %th Price unpacked
      %th{:colspan => "3"}
  %tbody
    - @product_packeds.each do |product_packed|
      %tr
        %td= product_packed.id
        %td= product_packed.name
        %td= product_packed.description
        %td= product_packed.url
        %td= product_packed.quantity_packed
        %td= product_packed.quantity_unpacked
        %td= product_packed.price_packed
        %td= product_packed.price_unpacked
        %td= link_to 'Show', product_packed
        %td= link_to 'Edit', edit_product_packed_path(product_packed)
        %td= link_to 'Destroy', product_packed, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Product packed', new_product_packed_path

app/views/admin/product_packeds/new.html.haml
%h1 New product_packed
= render 'form'
= link_to 'Back', product_packeds_path

app/views/admin/product_packeds/show.html.haml
%p#notice= notice
%p
  %strong Id:
  = @product_packed.id
%p
  %strong Name:
  = @product_packed.name
%p
  %strong Description:
  = @product_packed.description
%p
  %strong Url:
  = @product_packed.url
%p
  %strong Quantity packed:
  = @product_packed.quantity_packed
%p
  %strong Quantity unpacked:
  = @product_packed.quantity_unpacked
%p
  %strong Price packed:
  = @product_packed.price_packed
%p
  %strong Price unpacked:
  = @product_packed.price_unpacked
= link_to 'Edit', edit_product_packed_path(@product_packed)
|
\#{link_to 'Back', product_packeds_path}