config/routes.rb
Rails.application.routes.draw do
  root 'main#get'

  get :admin, to: 'admin/admin_main#get'
  scope '/admin', module: 'admin' do
    resources :product_packeds, as: 'product_packeds'
    resources :products, as: 'products'
    resources :categories, as: 'categories'
  end
end

app/models/category.rb
class Category
  include Mongoid::Document
  recursively_embeds_many
  field :name, type: String
  field :description, type: String
  field :order, type: Integer
  embeds_many :category_products

  def products(ass_filter = nil, include_children: false)
    list = Array.new
    category_products.each do | p |
      begin
        list << p.product if ass_filter.nil? or ass_filter == p.association
      rescue Mongoid::Errors::DocumentNotFound
      end
    end
    if include_children
      child_categories.each do |cc|
        list += cc.products
      end
    end
    list
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :order)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :order)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :order
    %br/
    = f.number_field :order
  .actions
    = f.submit

app/views/admin/categories/edit.html.haml
%h1 Editing category
= render 'form'
= link_to 'Show', @category
|
\#{link_to 'Back', categories_path}

app/views/admin/categories/index.html.haml
%h1 Listing categories
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Order
      %th{:colspan => "3"}
  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.description
        %td= category.order
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Category', new_category_path

app/views/admin/categories/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/admin/categories/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @category.name
%p
  %strong Description:
  = @category.description
%p
  %strong Order:
  = @category.order
= link_to 'Edit', edit_category_path(@category)
|
\#{link_to 'Back', categories_path}